apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - route.yaml

helmCharts:
  - name: rss3-node
    releaseName: rss3
    repo: https://naturalselectionlabs.github.io/helm-charts
    valuesFile: values.yaml
    version: 0.x.x
