hub:
  replicaCount: 2
database:
  uri: <path:kv/data/network/rss3-node#DATABASE_URI>
indexers:
  - network: farcaster
    worker: farcaster
    endpoint: <path:kv/data/network/rss3-node#FARCASTER_URI>
  - network: ethereum
    worker: rss3
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_ETHEREUM>
    parameters:
      block_number_start: 14748840
