hub:
  replicaCount: 2
database:
  uri: <path:kv/data/network/rss3-node#DATABASE_URI>
indexers:
  - network: farcaster
    worker: farcaster
    endpoint: <path:kv/data/network/rss3-node#FARCASTER_URI>
  - network: ethereum
    worker: rss3
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_ETHEREUM>
    parameters:
      block_number_start: 14748840
  - network: arweave
    endpoint: https://arweave.net/
    worker: mirror
    parameters:
      block_height_start: 1300034
      rpc_thread_blocks: 3
additionalRSS:
  - network: rss
    endpoint: https://rsshub.app/
    parameters:
      authentication:
        username:
        password:
        access_key:
        access_code:
