hub:
  replicaCount: 3
database:
  uri: <path:kv/data/network/rss3-node#DATABASE_URI>
indexers:
  - network: farcaster
    worker: farcaster
    endpoint: <path:kv/data/network/rss3-node#FARCASTER_URI>
  - network: ethereum
    worker: rss3
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_ETHEREUM>
    parameters:
      block_number_start: 14748840
  - network: polygon
    worker: lens
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_POLYGON>
    parameters:
      block_number_start: 48300005
  - network: ethereum
    worker: opensea
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_ETHEREUM>
    parameters:
      block_number_start: 17571053
  - network: ethereum
    worker: uniswap
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_ETHEREUM>
    parameters:
      block_number_start: 10207858
  - network: ethereum
    worker: optimism
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_ETHEREUM>
    parameters:
      block_number_start: 12686786
  - network: ethereum
    worker: fallback
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_ETHEREUM>
    parameters:
      block_number_start: 17571053
  - network: polygon
    worker: aavegotchi
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_POLYGON>
    parameters:
      block_number_start: 48300005
  - network: arweave
    endpoint: https://arweave.net/
    worker: mirror
    parameters:
      block_height_start: 1275799
      rpc_thread_blocks: 1
  - network: arweave
    endpoint: https://arweave.net/
    worker: paragraph
    parameters:
      block_height_start: 1275799
      rpc_thread_blocks: 1
  - network: ethereum
    worker: looksrare
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_ETHEREUM>
    parameters:
      block_number_start: 17571053
  - network: arweave
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_POLYGON>
    worker: momoka
    parameters:
      block_height_start: 1275799
      rpc_thread_blocks: 1
  - network: ethereum
    worker: lido
    endpoint: <path:kv/data/network/rss3-node#ENDPOINT_ETHEREUM>
    parameters:
      block_number_start: 17571053
additionalRSS:
  - network: rss
    endpoint: https://rsshub.app/
    parameters:
      authentication:
        username:
        password:
        access_key:
        access_code:
observability:
  opentelemetry:
    metrics:
      enable: true
      endpoint: 0.0.0.0:9090
    traces:
      enable: true
      insecure: true
      endpoint: jaeger-collector.guardian.svc:4318
global:
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
