environment: development

discovery:
  maintainer:
    owner_evm_address: "0x123" # address to receive network incentivization and ownership verification
    website: "https://abc.com/rss3-node" # link to your website
  server:
    # endpoint is how the Global Indexer reaches your RSS3 node
    # a domain name is recommended but not required, you can use an IP address+port as well
    endpoint: "https://rss3.abc.com/"
    signature: ""
    authentication:
      access_key: ""

database:
  driver: cockroachdb
  partition: true
  uri: postgres://root@localhost:26257/defaultdb

component:
  rss:
    - network: rsshub
      endpoint: https://rsshub.app/
      parameters:
        authentication:
          username:
          password:
          access_key:
          access_code:

  decentralized:
    - network: ethereum
      worker: fallback
      endpoint: https://rpc.ankr.com/eth
    - network: ethereum
      worker: rss3
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
        block_number_target:
    - network: farcaster
      worker: farcaster
      endpoint: https://nemes.farcaster.xyz:2281
