environment: development

discovery:
  maintainer:
    owner_evm_address: "0x123" # address to receive network incentivization and ownership verification
    website: "https://abc.com/rss3-node" # link to your website
  server:
    # endpoint is how the Global Indexer reaches your RSS3 node
    # a domain name is recommended but not required, you can use an IP address+port as well
    endpoint: "https://rss3.abc.com/"
    signature: ""
    authentication:
      access_key: ""

database:
  driver: cockroachdb
  partition: true
  uri: postgres://root@localhost:26257/defaultdb

stream:
  enable: false
  driver: kafka
  topic: rss3.node.feeds
  uri: localhost:9092

component:
  rss:
    - network: rss
      endpoint: https://rsshub.app/
      parameters:
        authentication:
          username:
          password:
          access_key:
          access_code:

  decentralized:
    # ethereum
    - network: ethereum
      worker: fallback
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
        block_number_target:
    - network: ethereum
      worker: rss3
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
        block_number_target:
    - network: polygon
      worker: lens
      endpoint: https://rpc.ankr.com/polygon
      ipfs_gateways:
      parameters:
        block_number_start:
    - network: ethereum
      worker: opensea
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: ethereum
      worker: uniswap
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: ethereum
      worker: optimism
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: polygon
      worker: aavegotchi
      endpoint: https://rpc.ankr.com/polygon
      parameters:
          block_number_start: 48300005
    # farcaster
    - network: farcaster
      worker: farcaster
      endpoint: https://nemes.farcaster.xyz:2281
    # arweave
    - network: arweave
      worker: mirror
      endpoint: https://arweave.net/
      ipfs_gateways:
      parameters:
        block_height_start:
        rpc_thread_blocks:
    - network: arweave
      worker: paragraph
      endpoint: https://arweave.net
      ipfs_gateways:
      parameters:
        block_height_start:
        rpc_thread_blocks:

    # iqwiki
    - network: polygon
      worker: iqwiki
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_number_start: 52070001
