discovery:
  version: "1.0.0"
  maintainer:
    owner_evm_address: "0x123"
    signature: "hello_world"
    website: "https://abc.com/rss3-node"
  node:
    endpoint: "https://rss3.abc.com/"
    access_key: "access_key"

config:
  hub:
    endpoint: "https://hub.abc.com/"
  environment: "development" # set to "production" when you are ready to go live
  node:
    network: arweave
    chain: mainnet
    endpoint: https://ethereum.blockpi.network/v1/rpc/public
  data:
    database:
      type: "CockroachDB"
      external: true
      host: "127.0.0.1"
      port: 5432
      username: "username"
      password: "password"
      database_name: "db"
  component:
    data:
      indexer_module:
        RSS:
          RSSHub:
            instance_url: "https://rsshub.app/"
            authentication:
              username: "username"
              password: "password"
              access_key: "access_key"
