environment: production

endpoints:
  ethereum:
    url: https://rpc.ankr.com/eth
    http_headers:
      user-agent: rss3-node
    http2_disabled:

discovery:
    maintainer:
      evm_address:
      signature:
    server:
      endpoint:
      global_indexer_endpoint:

database:
  driver: cockroachdb
  partition: true
  uri: postgres://root@localhost:26257/defaultdb

stream:
  enable: false
  driver: kafka
  topic: rss3.node.activities
  uri: localhost:9092

redis:
  endpoints:
    - localhost:6379
  username:
  password:
  disable_cache: true
  tls:
    enabled: false
    ca_file: /path/to/ca.crt
    cert_file: /path/to/client.crt
    key_file: /path/to/client.key
    insecure_skip_verify: false

observability:
  opentelemetry:
    metrics:
      enable: true
      endpoint: 0.0.0.0:9090
    traces:
      enable: true
      insecure: true
      endpoint: localhost:4318

component:
  rss:
    - network: rss
      endpoint: https://rsshub.app/
      parameters:
        authentication:
          access_key:

  decentralized:
    # ethereum
    - network: ethereum
      worker: core
      endpoint: ethereum
      parameters:
        block_number_start:
    - network: ethereum
      worker: rss3
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
        block_number_target:
    - network: polygon
      worker: lens
      endpoint: https://rpc.ankr.com/polygon
      ipfs_gateways:
      parameters:
        block_number_start:
    - network: ethereum
      worker: opensea
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: ethereum
      worker: uniswap
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: ethereum
      worker: optimism
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: polygon
      worker: aavegotchi
      endpoint: https://rpc.ankr.com/polygon
      parameters:
          block_number_start: 48300005
    - network: ethereum
      worker: highlight
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: arbitrum
      worker: highlight
      endpoint: https://rpc.ankr.com/arbitrum
      parameters:
        block_number_start:
    - network: polygon
      worker: highlight
      endpoint: https://rpc.ankr.com/polygon
      parameters:
          block_number_start:
    - network: optimism
      worker: highlight
      endpoint: https://rpc.ankr.com/optimism
      parameters:
        block_number_start:
    - network: crossbell
      worker: crossbell
      endpoint: https://rpc.crossbell.io
      parameters:
        block_number_start:
    # farcaster
    - network: farcaster
      worker: core
      endpoint: https://nemes.farcaster.xyz:2281
      parameters:
        api_key:
    # arweave
    - network: arweave
      worker: mirror
      endpoint: https://arweave.net/
      ipfs_gateways:
      parameters:
        block_height_start:
        rpc_thread_blocks:
    - network: arweave
      worker: paragraph
      endpoint: https://arweave.net/
      ipfs_gateways:
      parameters:
        block_height_start:
        rpc_thread_blocks:
    - network: ethereum
      worker: looksrare
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: polygon
      worker: matters
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_number_start:
    - network: arweave
      worker: momoka
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_height_start:
        rpc_thread_blocks:
    - network: ethereum
      endpoint: https://rpc.ankr.com/eth
      worker: aave
      parameters:
        block_number_start:
    - network: polygon
      endpoint: https://rpc.ankr.com/polygon
      worker: aave
      parameters:
        block_number_start:
    - network: avax
      endpoint: https://rpc.ankr.com/avalanche
      worker: aave
      parameters:
        block_number_start:
    - network: base
      endpoint: https://rpc.ankr.com/base
      worker: aave
      parameters:
        block_number_start:
    - network: optimism
      endpoint: https://rpc.ankr.com/optimism
      worker: aave
      parameters:
        block_number_start:
    - network: arbitrum
      endpoint: https://rpc.ankr.com/arbitrum
      worker: aave
      parameters:
        block_number_start:
    - network: polygon
      worker: iqwiki
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_number_start:
    - network: ethereum
      endpoint: https://rpc.ankr.com/eth
      worker: lido
      parameters:
        block_number_start:
    - network: ethereum
      endpoint: https://rpc.ankr.com/eth
      worker: ens
      parameters:
        block_number_start:
    - network: ethereum
      worker: 1inch
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: vsl
      endpoint: https://rpc.rss3.io
      worker: core
      parameters:
        block_number_start:
    - network: optimism
      endpoint: https://rpc.ankr.com/optimism
      worker: kiwistand
      parameters:
        block_number_start:
    - network: savm
      endpoint: https://alpha-rpc-node-http.svmscan.io
      worker: core
      parameters:
        block_number_start:
    - network: savm
      endpoint: https://alpha-rpc-node-http.svmscan.io
      worker: uniswap
      parameters:
        block_number_start:
    - network: savm
      endpoint: https://alpha-rpc-node-http.svmscan.io
      worker: savm
      parameters:
        block_number_start:
    - network: optimism
      endpoint: https://rpc.ankr.com/optimism
      worker: core
      parameters:
        block_number_start:
    - network: polygon
      endpoint: https://rpc.ankr.com/polygon
      worker: core
      parameters:
        block_number_start:
    - network: arbitrum
      endpoint: https://rpc.ankr.com/arbitrum
      worker: core
      parameters:
        block_number_start:
    - network: base
      endpoint: https://developer-access-mainnet.base.orgss
      worker: core
      parameters:
        block_number_start:
    - network: binance-smart-chain
      endpoint: https://rpc.ankr.com/bsc
      worker: core
      parameters:
        block_number_start: 34436412
        rpc_thread_blocks: 1
    - network: gnosis
      endpoint: https://rpc.ankr.com/gnosis
      worker: core
      parameters:
        block_number_start:
    - network: linea
      endpoint: https://rpc.linea.build
      worker: core
      parameters:
          block_number_start:
    - network: linea
      endpoint: https://rpc.linea.build
      worker: uniswap
      parameters:
        block_number_start:
    - network: vsl
      endpoint: https://rpc.rss3.io
      worker: rss3
    - network: ethereum
      worker: vsl
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: ethereum
      worker: stargate
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: arbitrum
      worker: stargate
      endpoint: https://rpc.ankr.com/arbitrum
      parameters:
        block_number_start:
    - network: linea
      endpoint: https://rpc.linea.build
      worker: stargate
      parameters:
        block_number_start:
    - network: binance-smart-chain
      endpoint: https://rpc.ankr.com/bsc
      worker: stargate
      parameters:
        block_number_start:
    - network: base
      endpoint: https://developer-access-mainnet.base.orgss
      worker: stargate
      parameters:
        block_number_start:
    - network: optimism
      endpoint: https://rpc.ankr.com/optimism
      worker: stargate
      parameters:
        block_number_start:
    - network: polygon
      worker: stargate
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_number_start:
    - network: avax
      endpoint: https://rpc.ankr.com/avalanche
      worker: stargate
      parameters:
        block_number_start:
    - network: ethereum
      worker: curve
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - network: arbitrum
      worker: curve
      endpoint: https://rpc.ankr.com/arbitrum
      parameters:
        block_number_start:
    - network: avax
      endpoint: https://rpc.ankr.com/avalanche
      worker: curve
      parameters:
        block_number_start:
    - network: gnosis
      endpoint: https://rpc.ankr.com/gnosis
      worker: curve
      parameters:
        block_number_start:
    - network: optimism
      worker: curve
      endpoint: https://rpc.ankr.com/optimism
      parameters:
        block_number_start:
    - network: polygon
      worker: curve
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_number_start:
