environment: production
type: beta

discovery:
    maintainer:
      evm_address:
      signature:
    server:
      endpoint:
      global_indexer_endpoint:

database:
  driver: cockroachdb
  partition: true
  uri: postgres://root@localhost:26257/node

stream:
  enable: false
  driver: kafka
  topic: rss3.node.activities
  uri: localhost:9092

redis:
  endpoints:
    - localhost:6379
  username:
  password:
  disable_cache: true
  tls:
    enabled: false
    ca_file: /path/to/ca.crt
    cert_file: /path/to/client.crt
    key_file: /path/to/client.key
    insecure_skip_verify: false

observability:
  opentelemetry:
    metrics:
      enable: true
      endpoint: 0.0.0.0:9090
    traces:
      enable: true
      insecure: true
      endpoint: localhost:4318

endpoints:
  ethereum:
    url: https://rpc.ankr.com/eth
  base:
    url: https://rpc.ankr.com/base
    http2_disabled: true

component:
  rss:
    - network: rss
      endpoint: https://rsshub.app/
      parameters:
        authentication:
          access_key:

  decentralized:
    - id: ethereum-core
      network: ethereum
      worker: core
      endpoint: ethereum
      parameters:
        block_number_start:
    - id: ethereum-rss3
      network: ethereum
      worker: rss3
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
        block_number_target:
    - id: polygon-lens
      network: polygon
      worker: lens
      endpoint: https://rpc.ankr.com/polygon
      ipfs_gateways:
      parameters:
        block_number_start:
    - id: ethereum-opensea
      network: ethereum
      worker: opensea
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - id: ethereum-uniswap
      network: ethereum
      worker: uniswap
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - id: ethereum-optimism
      network: ethereum
      worker: optimism
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - id: polygon-aavegotchi
      network: polygon
      worker: aavegotchi
      endpoint: https://rpc.ankr.com/polygon
      parameters:
          block_number_start: 48300005
    - id: ethereum-highlight
      network: ethereum
      worker: highlight
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - id: arbitrum-highlight
      network: arbitrum
      worker: highlight
      endpoint: https://rpc.ankr.com/arbitrum
      parameters:
        block_number_start:
    - id: polygon-highlight
      network: polygon
      worker: highlight
      endpoint: https://rpc.ankr.com/polygon
      parameters:
          block_number_start:
    - id: optimism-highlight
      network: optimism
      worker: highlight
      endpoint: https://rpc.ankr.com/optimism
      parameters:
        block_number_start:
    - id: crossbell-crossbell
      network: crossbell
      worker: crossbell
      endpoint: https://rpc.crossbell.io
      parameters:
        block_number_start:
    # farcaster
    - id: farcaster-core
      network: farcaster
      worker: core
      endpoint: https://nemes.farcaster.xyz:2281
      parameters:
        api_key:
    # arweave
    - id: arweave-mirror
      network: arweave
      worker: mirror
      endpoint: https://arweave.net/
      ipfs_gateways:
      parameters:
        block_height_start:
        rpc_thread_blocks:
    - id: arweave-paragraph
      network: arweave
      worker: paragraph
      endpoint: https://arweave.net/
      ipfs_gateways:
      parameters:
        block_height_start:
        rpc_thread_blocks:
    - id: ethereum-looksrare
      network: ethereum
      worker: looksrare
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - id: polygon-matters
      network: polygon
      worker: matters
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_number_start:
    - id: arweave-momoka
      network: arweave
      worker: momoka
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_height_start:
        rpc_thread_blocks:
    - id: ethereum-aave
      network: ethereum
      endpoint: https://rpc.ankr.com/eth
      worker: aave
      parameters:
        block_number_start:
    - id: polygon-aave
      network: polygon
      endpoint: https://rpc.ankr.com/polygon
      worker: aave
      parameters:
        block_number_start:
    - id: avax-aave
      network: avax
      endpoint: https://rpc.ankr.com/avalanche
      worker: aave
      parameters:
        block_number_start:
    - id: base-aave
      network: base
      endpoint: https://rpc.ankr.com/base
      worker: aave
      parameters:
        block_number_start:
    - id: optimism-aave
      network: optimism
      endpoint: https://rpc.ankr.com/optimism
      worker: aave
      parameters:
        block_number_start:
    - id: arbitrum-aave
      network: arbitrum
      endpoint: https://rpc.ankr.com/arbitrum
      worker: aave
      parameters:
        block_number_start:
    - id: polygon-iqwiki
      network: polygon
      worker: iqwiki
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_number_start:
    - id: ethereum-lido
      network: ethereum
      endpoint: https://rpc.ankr.com/eth
      worker: lido
      parameters:
        block_number_start:
    - id: ethereum-ens
      network: ethereum
      endpoint: https://rpc.ankr.com/eth
      worker: ens
      parameters:
        block_number_start:
    - id: ethereum-1inch
      network: ethereum
      worker: 1inch
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - id: vsl-core
      network: vsl
      endpoint: https://rpc.rss3.io
      worker: core
      parameters:
        block_number_start:
    - id: optimism-kiwistand
      network: optimism
      endpoint: https://rpc.ankr.com/optimism
      worker: kiwistand
      parameters:
        block_number_start:
    - id: savm-core
      network: savm
      endpoint: https://alpha-rpc-node-http.svmscan.io
      worker: core
      parameters:
        block_number_start:
    - id: savm-uniswap
      network: savm
      endpoint: https://alpha-rpc-node-http.svmscan.io
      worker: uniswap
      parameters:
        block_number_start:
    - id: savm-savm
      network: savm
      endpoint: https://alpha-rpc-node-http.svmscan.io
      worker: savm
      parameters:
        block_number_start:
    - id: optimism-core
      network: optimism
      endpoint: https://rpc.ankr.com/optimism
      worker: core
      parameters:
        block_number_start:
    - id: polygon-core
      network: polygon
      endpoint: https://rpc.ankr.com/polygon
      worker: core
      parameters:
        block_number_start:
    - id: arbitrum-core
      network: arbitrum
      endpoint: https://rpc.ankr.com/arbitrum
      worker: core
      parameters:
        block_number_start:
    - id: base-core
      network: base
      endpoint: base
      worker: core
      parameters:
        block_number_start:
    - id: binance-smart-chain-core
      network: binance-smart-chain
      endpoint: https://rpc.ankr.com/bsc
      worker: core
      parameters:
        block_number_start: 34436412
        rpc_thread_blocks: 1
    - id: gnosis-core
      network: gnosis
      endpoint: https://rpc.ankr.com/gnosis
      worker: core
      parameters:
        block_number_start:
    - id: linea-core
      network: linea
      endpoint: https://rpc.linea.build
      worker: core
      parameters:
          block_number_start:
    - id: linea-uniswap
      network: linea
      endpoint: https://rpc.linea.build
      worker: uniswap
      parameters:
        block_number_start:
    - id: vsl-rss3
      network: vsl
      endpoint: https://rpc.rss3.io
      worker: rss3
    - id: ethereum-vsl
      network: ethereum
      worker: vsl
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - id: ethereum-stargate
      network: ethereum
      worker: stargate
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - id: arbitrum-stargate
      network: arbitrum
      worker: stargate
      endpoint: https://rpc.ankr.com/arbitrum
      parameters:
        block_number_start:
    - id: linea-stargate
      network: linea
      endpoint: https://rpc.linea.build
      worker: stargate
      parameters:
        block_number_start:
    - id: binance-smart-chain-stargate
      network: binance-smart-chain
      endpoint: https://rpc.ankr.com/bsc
      worker: stargate
      parameters:
        block_number_start:
    - id: base-stargate
      network: base
      endpoint: https://developer-access-mainnet.base.orgss
      worker: stargate
      parameters:
        block_number_start:
    - id: optimism-stargate
      network: optimism
      endpoint: https://rpc.ankr.com/optimism
      worker: stargate
      parameters:
        block_number_start:
    - id: polygon-stargate
      network: polygon
      worker: stargate
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_number_start:
    - id: avax-stargate
      network: avax
      endpoint: https://rpc.ankr.com/avalanche
      worker: stargate
      parameters:
        block_number_start:
    - id: ethereum-curve
      network: ethereum
      worker: curve
      endpoint: https://rpc.ankr.com/eth
      parameters:
        block_number_start:
    - id: arbitrum-curve
      network: arbitrum
      worker: curve
      endpoint: https://rpc.ankr.com/arbitrum
      parameters:
        block_number_start:
    - id: avax-curve
      network: avax
      endpoint: https://rpc.ankr.com/avalanche
      worker: curve
      parameters:
        block_number_start:
    - id: gnosis-curve
      network: gnosis
      endpoint: https://rpc.ankr.com/gnosis
      worker: curve
      parameters:
        block_number_start:
    - id: optimism-curve
      network: optimism
      worker: curve
      endpoint: https://rpc.ankr.com/optimism
      parameters:
        block_number_start:
    - id: polygon-curve
      network: polygon
      worker: curve
      endpoint: https://rpc.ankr.com/polygon
      parameters:
        block_number_start:
