version: "3"

services:
  devcontainer:
    container_name: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    command: sleep infinity
  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:v23.1.8
    networks:
      - default
    ports:
      - "8080:8080"
      - "26257:26257"
    volumes:
      - "cockroachdb:/cockroach/cockroach-data"
    command:
      - start-single-node
      - --cluster-name=rss3-node
      - --insecure
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.49.0
    networks:
      - default
    ports:
      - "4317:4317" # OpenTelemetry Protocol over gRPC
      - "4318:4318" # OpenTelemetry Protocol over HTTP
      - "5778:5778" # Configurations
      - "16686:16686" # Frontend
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

volumes:
  cockroachdb:
  jaeger:

networks:
  default:
