# Default configuration file for the RSS3 Node.
environment: production
type: normal

discovery:
  operator:
    evm_address: 0x...address
    signature: 0x...signature
  server:
    endpoint: https://your.node.com
    global_indexer_endpoint: https://gi.rss3.io
    access_token: your_access_token

database:
  driver: cockroachdb
  partition: true
  uri: postgres://root@localhost:26257/defaultdb

redis:
  endpoint: localhost:6379
  username:
  password:
  disable_cache: true
  tls:
    enabled: false
    ca_file: /path/to/ca.crt
    cert_file: /path/to/client.crt
    key_file: /path/to/client.key
    insecure_skip_verify: false

stream:
  enable: false
  driver: kafka
  topic: rss3.node.activities
  uri: localhost:9092

observability:
  opentelemetry:
    metrics:
      enable: false
      endpoint: 0.0.0.0:9090
    traces:
      enable: false
      endpoint: localhost:4318
      insecure: true

endpoints:
  vsl:
    url: https://rpc.rss3.io

component:
  rss:
    id: rss-rsshub
    network: rss
    worker: rsshub
    endpoint: https://your.rsshub.com/
    parameters:
      authentication:
        access_key:
  decentralized:
    - id: vsl-core
      network: vsl
      endpoint: vsl
      worker: core
