name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  # For pr test only, remove this before merging to develop
  pull_request:

jobs:
  update-readme:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pathlib

      - name: Update README
        run: |
          python build_readme.py

      - name: Check if README has changed
        id: check_readme
        run: |
          if git diff --quiet README.md; then
            echo "README has not changed"
            echo "::set-output name=changed::false"
          else
            echo "README has changed"
            echo "::set-output name=changed::true"
          fi

      - name: Generate datetime string for PR title
        id: datetime
        run: echo "::set-output name=datetime::$(date +'%Y%m%d%H%M')"

      - name: Commit and push changes to a new branch
        if: steps.check_readme.outputs.changed == 'true'
        run: |
          git config --global user.email "pseudoyu@connect.hku.hk"
          git config --global user.name "pseudoyu"
          git checkout -b update-readme-${{ steps.datetime.outputs.datetime }}
          git add README.md
          git commit -m "doc: update supported network and worker in README.md"
          git push origin update-readme-${{ steps.datetime.outputs.datetime }}

      - name: Close existing pull requests
        if: steps.check_readme.outputs.changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });

            for (const pr of pullRequests) {
              if (pr.title.startsWith('ci(README.md): update supported network and worker')) {
                await github.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  state: 'closed',
                });

                await github.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: "This pull request has been closed to make way for a new update.",
                });
              }
            }

      - name: Create Pull Request
        if: steps.check_readme.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "doc: update supported network and worker in README.md"
          branch: update-readme-${{ steps.datetime.outputs.datetime }}
          title: "ci(README.md): update supported network and worker (${{ steps.datetime.outputs.datetime }})"
          body: "This PR updates the README.md file with the latest supported network and worker information."
          base: develop
