name: Update README

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/network/rss3-node GLOBAL_INDEXER_ENDPOINT

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pathlib

      - name: Update README
        run: |
          python build_readme.py

      - name: Commit and push if changed
        run: |
          git diff
          if git diff --quiet; then
            echo "No changes to README.md, skipping commit."
          else
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git add README.md
            git commit -m doc: update supported network and worker in README.md"
            git push
          fi
