name: build & deploy

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: rss3/node
      context: .
      dockerfile: ./Dockerfile
    secrets: inherit
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/node
      tag: sha-${{ github.sha }}
      cluster: dev
      namespace: network
      releaseName: rss3-node
      revision: develop
      dir: deploy/dev
    secrets: inherit
  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/node
      tag: ${{ github.ref_name }}
      cluster: prod
      namespace: network
      releaseName: rss3-node
      revision: ${{ github.ref_name }}
      dir: deploy/prod
    secrets: inherit