name: build & deploy

on:
  push:
    branches:
      - "develop"
    tags:
      - "*"

jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    with:
      images: rss3/node
      context: .
      dockerfile: ./Dockerfile
      platforms: ${{ matrix.platform }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}