name: build & deploy

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: rss3/node
      context: .
      dockerfile: ./Dockerfile
    secrets: inherit
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/node
      tag: sha-${{ github.sha }}
      cluster: dev
      namespace: network
      releaseName: rss3-node
      revision: develop
      dir: deploy/dev
    secrets: inherit