name: Test
on:
  workflow_run:
    workflows:
      - Lint
    types:
      - completed


jobs:
  test:
    name: Test
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/network/rss3-node ENDPOINT_ETHEREUM ;
            kv/data/network/rss3-node ENDPOINT_POLYGON ;
            kv/data/network/rss3-node FARCASTER_URI
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://git:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: make test
